export const rankLabels: Record<string, string> = {
  Sestra_miloserdiya: "Сестра милосердия",
  Chinovnik: "Чиновник",
  Chinovnik_voennogo_vedomstva: "Чиновник военного ведомства",
  Nizhniy_chin: "Нижний чин",
  Ofitser: "Офицер",
  Ryadovoy: "Рядовой",
  Efreytor: "Ефрейтор",
  Mladshiy_unter_ofitser: "Младший унтер-офицер",
  Starshiy_unter_ofitser: "Старший унтер-офицер",
  Feldfebel: "Фельдфебель",
  Podpraporshchik: "Подпрапорщик",
  Praporshchik: "Прапорщик",
  Podporuchik: "Подпоручик",
  Poruchik: "Поручик",
  Shtab_kapitan: "Штаб-капитан",
  Kapitan: "Капитан",
  Podpolkovnik: "Подполковник",
  Polkovnik: "Полковник",
  General_mayor: "Генерал-майор",
  General_leytenant: "Генерал-лейтенант",
  General_ot_infanterii: "Генерал от инфантерии",
  Kanonir: "Канонир",
  Bombardir: "Бомбардир",
  Mladshiy_feyerverker: "Младший фейерверкер",
  Starshiy_feyerverker: "Старший фейерверкер",
  Vakhmistr: "Вахмистр",
  General_ot_kavalerii: "Генерал от кавалерии",
  Kazak: "Казак",
  Mladshiy_uryadnik: "Младший урядник",
  Starshiy_uryadnik: "Старший урядник",
  Khorunzhiy: "Хорунжий",
  Sotnik: "Сотник",
  Podesaul: "Подъесаул",
  Esaul: "Есаул",
  Voyskovoy_starshina: "Войсковой старшина",
  Matros: "Матрос",
  Kvartirmeyster: "Квартирмейстер",
  Botsman: "Боцман",
  Konduktor: "Кондуктор",
  Kapitan_2_ranga: "Капитан 2 ранга",
  Kapitan_1_ranga: "Капитан 1 ранга",
  Kontr_admiral: "Контр-адмирал",
  Vitse_admiral: "Вице-адмирал",
  Admiral: "Адмирал",
  Michman: "Мичман",
  Leytenant: "Лейтенант",
  Starshiy_leytenant: "Старший лейтенант",
  Kollezhskiy_registrator: "Коллежский регистратор",
  Provintsialnyy_sekretar: "Провинциальный секретарь",
  Gubernskiy_sekretar: "Губернский секретарь",
  Kollezhskiy_sekretar: "Коллежский секретарь",
  Titulyarnyy_sovetnik: "Титулярный советник",
  Kollezhskiy_asesor: "Коллежский асессор",
  Nadvornyy_sovetnik: "Надворный советник",
  Kollezhskiy_sovetnik: "Коллежский советник",
  Taynyy_sovetnik: "Тайный советник",
  Deystvitelnyy_statskiy_sovetnik: "Действительный статский советник",
  Statskiy_sovetnik: "Статский советник",
  Deystvitelnyy_taynyy_sovetnik: "Действительный тайный советник",
};
